- name: Run API Tests
  run: |
    mkdir -p reports

    newman run "Loja Virtual.postman_collection.json" \
      -e "baseUrl.postman_environment.json" \
      -r cli,htmlextra \
      --reporter-htmlextra-export reports/index.html
